### PR TITLE
Update toolbar icons to better fit the new UI

### PR DESCRIPTION
**Pull request by almas-x**
Before
image
After
iShot_2022-12-10_16 46 01

### CODE REVIEW

**Comment by uwolfer** [comment]
@almas1992: Thanks for your PR! Have you created this icon yourself? I'm asking because of possible licencing issues.

**Comment by almas-x** [comment]
> @almas1992: Thanks for your PR! Have you created this icon yourself? I'm asking because of possible licencing issues.

Yes, but I just did it based on the original icon

**Comment by uwolfer** [comment]
After checking IntelliJ docs, it looks like we should move to SVG icons:
https://plugins.jetbrains.com/docs/intellij/work-with-icons-and-images.html#svg-format

SVGs are only supported for 2018.2; if you go the SVG way, please create [intellij2020.3](https://github.com/uwolfer/gerrit-intellij-plugin/tree/intellij2020.3) branch.

**Comment by uwolfer** [comment]
I have tried to create an SVG like you did, based on pluginIcon.svg. I am not completely happy, I think yours looks better. But I also noticed that you are using the new UI styling, which uses bigger icons.

My version:
gerrit

**Comment by almas1992** [comment]
> 

Because I don't know the icon directory structure of intellij2020.3, I turned off PR.So I'll take the time to make the svg version of the icon, and you help integrate it into the plugin, do you think it's OK?

**Comment by almas-x** [comment]
> I have tried to create an SVG like you did, based on pluginIcon.svg. I am not completely happy, I think yours looks better. But I also noticed that you are using the new UI styling, which uses bigger icons.
> 
> My version: gerrit

I create svg icon and submit a new PR #471

**Pull request closed without merging**
